name: Browserstack

on:
  push:
    branches:
      - main

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  test:
    runs-on: ubuntu-latest
    environment: browserstack
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      NODE_VERSION: 24.x
    name: ${{ matrix.BROWSER }}
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.BROWSER }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        BROWSER:
          - 'IE_11'
          # BrowserStack makes Safari on beta macOS versions available without marking
          # either the OS or the browser as beta, so we have no way to resolve "latest"
          # to the lastest stable version. Given that major Safari version updates
          # only come once a year, we'll just keep updating them each year, together
          # with related iOS versions.
          - 'Safari_27'
          - 'Safari_26'
          - 'Chrome_latest'
          - 'Chrome_latest-1'
          - 'Opera_latest'
          - 'Edge_latest'
          - 'Edge_latest-1'
          - 'Firefox_latest'
          - 'Firefox_latest-1'
          - '_:iPhone 18 Pro_iOS_27'
          - '_:iPhone 17_iOS_26'
          - '_:iPhone 16_iOS_18'
          - '_:iPad 10th_iOS_27'
          - '_:iPad Pro 11 2025_iOS_26'
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Build jQuery
        run: npm run build:all

      - name: Pretest script
        run: npm run pretest

      - name: Run tests
        run: |
          npm run test:unit -- -v -c jtr-isolate.yml \
            --browserstack "${{ matrix.BROWSER }}" \
            --run-id ${{ github.run_id }}
